---
# Master-Playbook: vollst√§ndige Provisionierung eines Paperless-Hosts

- name: Setup system + Docker + Paperless
  hosts: ubuntu
  become: true

  roles:
    - common      # System-Basis, Firewall, Updates, Tools
    - docker      # Docker Engine, docker-compose-plugin etc.
    - paperless   # Paperless-Stack (docker-compose)
