# Basis-Einstellungen für Paperless
paperless_root: /paperless                    # Wo soll Paperless im Filesystem installiert werden?
paperless_http_port: 80                       # Unter welchem Port soll Paperless laufen?
paperless_image_tag: "2.19.6"                 # Welche Version soll installiert werden?
PAPERLESS_URL: "http://paperless.home.local"

# Der Benutzer, mit dem die Installation durchgeführt wird und die Dienste gestartet werden
# System-User/Gruppe, dem die Dateien gehören sollen
## Der User muss vorher auf dem Betriebssystem existieren und sudo-Befehle ausführen dürfen
paperless_system_user: paperless
paperless_system_group: paperless

# Erlaubte Firewall-Ports setzen
firewall_allowed_tcp_ports:
  - 21      # FTP
  - 22      # SSH
  - 80      # Paperless HTTP
  - 443     # HTTPS (für später)
  - "50000:50010"      # FTP passive data ports

# Superuser/Admin
paperless_admin_user: admin               # Das ist der User, mit dem du dich an Paperless in der GUI anmeldest.
paperless_admin_password: "Test1234"
paperless_admin_email: admin@example.com
