# Ansible-User: mit disen User wird die Installation durchgeführt.
## Dieser User muss auf dem Zielsystem existieren und kann mit den folgenden Befehlen angelegt werden
# sudo adduser ansible
# sudo usermod -aG sudo ansible
# sudo visudo -f /etc/sudoers.d/ansible
# ansible ALL=(ALL) NOPASSWD: ALL
# sudo chmod 440 /etc/sudoers.d/ansible

ansible_user: ansible  # Dieser Benutzer muss zuvor auf dem Ubuntu-Server existieren und sudo dürfen.


# Basis-Einstellungen für Paperless
paperless_root: /paperless                    # Wo soll Paperless im Filesystem installiert werden?
paperless_http_port: 80                       # Unter welchem Port soll Paperless laufen?
paperless_image_tag: "2.19.6"                 # Welche Version soll installiert werden?
paperless_hostname: "paperless.home.local"
paperless_ip: "172.16.249.152"
PAPERLESS_URL: "http://{{ paperless_hostname }}"

# Der Benutzer, der für den Service verwendet wird und die Dienste gestartet werden.
# System-User/Gruppe, dem die Dateien gehören sollen
## Der User muss vorher auf dem Betriebssystem existieren und sudo-Befehle ausführen dürfen
paperless_system_user: paperless
paperless_system_group: paperless

# Erlaubte Firewall-Ports setzen
firewall_allowed_tcp_ports:
  - 21      # FTP
  - 22      # SSH
  - 80      # Paperless HTTP
  - 443     # HTTPS (für später)
  - "50000:50010"      # FTP passive data ports

# Superuser/Admin
paperless_admin_user: admin               # Das ist der User, mit dem du dich an Paperless in der GUI anmeldest.
paperless_admin_password: "Test1234"
paperless_admin_email: admin@example.com
