# Basis-Einstellungen für Paperless
## Wo soll Paperless installiert werden?
## Unter welchem Port soll Paperless laufen?
## Welche Version soll installiert werden?
paperless_root: /paperless
paperless_http_port: 80
paperless_image_tag: "2.19.6"
PAPERLESS_URL: "http://paperless.home.local"

# Der Benutzer, mit dem die Installation durchgeführt wird und die Dienste gestartet werden
# System-User/Gruppe, dem die Dateien gehören sollen
## Der User muss vorher auf dem Betriebssystem existieren und sudo-Befehle ausführen dürfen
paperless_system_user: paperless
paperless_system_group: paperless

# Erlaubte Firewall-Ports setzen
firewall_allowed_tcp_ports:
  - 22      # SSH
  - 80      # Paperless HTTP
  - 443     # HTTPS (für später)

# Superuser/Admin
paperless_admin_user: admin
paperless_admin_password: "Test1234"
paperless_admin_email: admin@example.com
