paperless_root: /paperless
paperless_http_port: 80
paperless_image_tag: "2.19.6"

# Erlaubte Firewall-Ports setzen
firewall_allowed_tcp_ports:
  - 22      # SSH
  - 80      # Paperless HTTP
  - 443     # HTTPS (für später)

# Superuser/Admin
paperless_admin_user: admin
paperless_admin_password: "Test1234"
paperless_admin_email: admin@example.com
