---
# Basis-Root für alles von Paperless
paperless_root: /paperless

# Superuser/Admin
paperless_admin_user: admin
paperless_admin_password: "CHANGEME!"
paperless_admin_email: admin@example.com


# Name des Stack-Verzeichnisses (unterhalb von paperless_root)
paperless_stack_dir_name: docker

# Ableitungen aus den obigen Werten
paperless_stack_dir: "{{ paperless_root }}/{{ paperless_stack_dir_name }}"
paperless_data_dir: "{{ paperless_root }}/data"
paperless_db_dir: "{{ paperless_root }}/db"
paperless_backup_dir: "/paperless-backups"

# Ort für die Backup&Restore-Skripte selbst
paperless_backup_scripts_dir: "{{ paperless_backup_dir }}/scripts"

# Ort für Skripte
paperless_scripts_dir: "{{ paperless_root }}/scripts"

# Ob beim Restore automatisch docker compose down/up gemacht werden soll
paperless_restore_manage_docker: true

# Unterordner für Daten
paperless_media_dir: "{{ paperless_data_dir }}/media"
paperless_appdata_dir: "{{ paperless_data_dir }}/data"
paperless_export_dir: "{{ paperless_data_dir }}/export"
paperless_consume_dir: "{{ paperless_data_dir }}/consume"

# VSFTPD-Temp-Ports
vsftpd_pasv_min_port: 50000
vsftpd_pasv_max_port: 50010

# Unterordner für DB
paperless_postgres_dir: "{{ paperless_db_dir }}/postgres"
paperless_redis_dir: "{{ paperless_db_dir }}/redis"

# System-User/Gruppe, dem die Dateien gehören sollen
paperless_system_user: paperless
paperless_system_group: paperless

# Docker / Paperless Einstellungen
paperless_image_tag: latest          # z.B. "latest" oder "2.19.6"
paperless_http_port: 80              # Externer Port für das Webinterface

# DB-Einstellungen
paperless_db_name: paperless
paperless_db_user: paperless
paperless_db_password: paperless     # In echt lieber per Ansible Vault o.ä. setzen
